#!/bin/sh

function _config() {

	if [ $# = 0 ]; then

		pwtext "_config: no option specified"
		exit 2

	fi

	while [ $# -gt 0 ]; do

		case "$1" in

			-s|--no-strip) echo "nostrip=yes" >> ${tmp}/config ;;
			*) pwtext "_config: invalid option - %s" $1 ; exit 2 ;;

		esac

		shift

	done

}
