#!/bin/sh

function _execindir() {

    prevdir="`pwd`"

    if [ -f ${tmp}/setexecdir ]; then

	    cd "`cat ${tmp}/setexecdir`"

    else

	    cd "$1"
	    shift

    fi

    env -i USER=$USER HOME=$HOME inotherdir=yes sh -l /usr/lib/pwbuilder/bin/xexec "$@"
    cd "${prevdir}"

}
