#!/bin/sh

function _pwbuilder_make_version() {

	ver_1=`echo $1 | cut -d '.' -f 1`
	ver_2=`echo $1 | cut -d '.' -f 2`
	ver_3=`echo $1 | cut -d '.' -f 3`

	echo `expr ${ver_1} \* 65536 + ${ver_2} \* 256 + ${ver_3} \* 1`

}

function _pwbuilder() {

	if [ "$1" = "" ]; then

		pwtext "_pwbuilder: missing argument"
		exit 2

	fi

	if ! echo "$1" | egrep '^[0-9]+[.][0-9]+[.][0-9]+$' > /dev/null 2>&1; then

		pwtext "_pwbuilder: invalid version"
		exit 2

	fi

	required_version=`_pwbuilder_make_version $1`
	current_version=`_pwbuilder_make_version ${pwbuilder_version}`

	if [ "${required_version}" -gt "${current_version}" ]; then

		pwtext "! Error: your pwbuilder %s is too old (at least %s needed)" ${pwbuilder_version} $1
		exit 3

	fi

}
