#!/bin/sh

function _py_build() {

	srcnum="1"
	subdir=""
	opts=""
	otherdir=""

	while [ $# -gt 0 ]; do

		case "$1" in

			-s) shift ; srcnum="$1" ;;
			-b) shift ; subdir="$1" ;;
			-d) shift ; otherdir="$1" ;;
			*) opts="${opts} $1" ;;

		esac

		shift

	done

	if [ "${inotherdir}" = "yes" ]; then

		pwtext "_py_build: must not be invoked with _execindir; use -d instead"
		exit 2

	fi

	eval "srcd=\"\${src${srcnum}}\""

	(

		if [ "${otherdir}" = "" ]; then

			cd ${srcd}/${subdir}

		else

			cd "${otherdir}"

		fi

		touch ${tmp}/py_b_opts_${srcnum}

		if [ "${pw_debug}" = "yes" ]; then

			echo "+ Python build #${srcnum} (python setup.py build "`cat ${tmp}/py_b_opts_${srcnum}` ${opts}")"
			_exec python setup.py build `cat ${tmp}/py_b_opts_${srcnum}` ${opts}
			echo $? > ${tmp}/pybures

		else

			echo "+ Python build #${srcnum}"
			_exec python setup.py build `cat ${tmp}/py_b_opts_${srcnum}` ${opts} > /dev/null
			echo $? > ${tmp}/pybures

		fi

	)

	if [ ! `cat ${tmp}/pybures` = 0 ]; then

		pwtext "! Error: python build failed"
		exit 3

	fi

}
