#!/bin/sh

function _py_install() {

	srcnum="1"
	subdir=""
	undefine=""
	opts=""
	otherdir=""

	while [ $# -gt 0 ]; do

		case "$1" in

			-s) shift ; srcnum="$1" ;;
			-b) shift ; subdir="$1" ;;
			-u) undefine="yes" ;;
			-d) shift ; otherdir="$1" ;;
			*) opts="${opts} $1" ;;

		esac

		shift

	done

	if [ "${inotherdir}" = "yes" ]; then

		pwtext "_py_install: must not be invoked with _execindir; use -d instead"
		exit 2

	fi

	eval "srcd=\"\${src${srcnum}}\""

	(

		if [ "${otherdir}" = "" ]; then

			cd ${srcd}/${subdir}

		else

			cd "${otherdir}"

		fi

		touch ${tmp}/py_i_opts_${srcnum}

		if [ ! "${undefine}" = "yes" ]; then

			destvars="--root=${pkg}"

		fi

		if [ "${pw_debug}" = "yes" ]; then

			echo "+ Python install #${srcnum} (python setup.py install "${destvars} `cat ${tmp}/py_i_opts_${srcnum}` ${opts}")"
			_exec python setup.py install ${destvars} `cat ${tmp}/py_i_opts_${srcnum}` ${opts}
			echo $? > ${tmp}/pyinres

		else

			echo "+ Python install #${srcnum}"
			_exec python setup.py install ${destvars} `cat ${tmp}/py_i_opts_${srcnum}` ${opts} > /dev/null
			echo $? > ${tmp}/pyinres

		fi

	)

	if [ ! `cat ${tmp}/pyinres` = 0 ]; then

		pwtext "! Error: python install failed"
		exit 3

	fi

}
